query ($dir: String!, $kind: AssetKind!) {
  assets {
    list(dir:$dir, kind: $kind) {
      id
      filename
      ext
      kind
      mime
      fileSize
      createdAt
      updatedAt
    }
  }
}
