# ===============================================
# ASSETS
# ===============================================

extend type Query {
  assets: AssetQuery
}

extend type Mutation {
  assets: AssetMutation
}

# -----------------------------------------------
# QUERIES
# -----------------------------------------------

type AssetQuery {
  list(
    dir: String!
    kind: AssetKind!
  ): [AssetItem] @auth(requires: ["manage:system", "read:assets"])

  folders: [String!] @auth(requires: ["manage:system", "read:assets"])
}

# -----------------------------------------------
# MUTATIONS
# -----------------------------------------------

type AssetMutation {
  renameAsset(
    id: Int!
    filename: String!
  ): DefaultResponse @auth(requires: ["manage:system", "manage:assets"])

  deleteAsset(
    id: Int!
  ): DefaultResponse @auth(requires: ["manage:system", "manage:assets"])

  flushTempUploads: DefaultResponse @auth(requires: ["manage:system"])
}

# -----------------------------------------------
# TYPES
# -----------------------------------------------

type AssetItem {
  id: Int!
  filename: String!
  ext: String!
  kind: AssetKind!
  mime: String!
  fileSize: Int!
  metadata: String
  createdAt: Date!
  updatedAt: Date!
  dir: String!
  author: User
}

enum AssetKind {
  IMAGE
  BINARY
  ALL
}
