when:
  branch: main
  event: [ manual ]

steps:
  deploy:
    image: docker
    environment:
      GHCR_TOKEN:
        from_secret: GHCR_TOKEN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/1panel/apps/wikijs/ffwiki:/opt/1panel/apps/wikijs/ffwiki
    commands:
      - |
        echo "$GHCR_TOKEN" | docker login ghcr.io -u Tigercrl --password-stdin
        docker pull ${IMAGE_NAME}

        cd /opt/1panel/apps/wikijs/ffwiki
        sed -i "s|image:.*|image: ${IMAGE_NAME}|" docker-compose.yml
        docker compose pull
        docker compose up -d --force-recreate --remove-orphans
        docker compose ps

        docker compose logs --tail=20
